name: Build Boyin Executable

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyttsx3 pygame pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=boyin boyin.py

    - name: Create folders structure
      run: |
        New-Item -Path "dist\提示音" -ItemType Directory -Force
        New-Item -Path "dist\音频文件" -ItemType Directory -Force
      shell: pwsh

    - name: Create README
      run: |
        @"
        定时播音系统 v1.0
        
        使用说明:
        1. 将提示音文件(如 tone-a.mp3, tone-b.mp3)放入"提示音"文件夹
        2. 将音频文件放入"音频文件"文件夹
        3. 双击运行 boyin.exe 开始使用
        
        功能特点:
        - 定时语音播报
        - 音频文件播放
        - 灵活的时间调度
        - 任务管理
        
        注意事项:
        - 首次运行需要等待语音引擎初始化
        - 支持的音频格式: MP3, WAV, OGG
        - 任务保存在 broadcast_tasks.json 文件中
        "@  | Out-File -FilePath "dist\README.txt" -Encoding UTF8
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: boyin-windows
        path: dist/

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/boyin.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
