# 工作流名称
name: Build Python Application

# 触发工作流的事件
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # 关键修复：强制使用 64 位 Python
      - name: Set up Python (forcing x64)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      # 关键修复：确保 pywin32 在构建环境中正确配置
      - name: Install and configure pywin32
        run: |
          python -m pip install --upgrade pip
          pip install pywin32
          python Scripts/pywin32_postinstall.py -install

      - name: Install other dependencies from requirements.txt
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build application with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name boyin boyin.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: boyin-Windows-x64
          path: dist/boyin.exe
