name: Build Python Application with Nuitka

on:
  push:
    branches: [ "main","master" ]
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - python-version: '3.8.10'
            architecture: 'x86'
            artifact-name: 'boyin-Windows-x86-for-Win7'
            output-dir-name: 'boyin_win32'

          - python-version: '3.8.10'
            architecture: 'x64'
            artifact-name: 'boyin-Windows-x64-for-Win7'
            output-dir-name: 'boyin_win64_py38'

          - python-version: '3.11'
            architecture: 'x64'
            artifact-name: 'boyin-Windows-x64-for-Win8.1+'
            output-dir-name: 'boyin_win64_py311'

    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} (${{ matrix.architecture }})
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
          architecture: '${{ matrix.architecture }}'
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-pip-${{ hashFiles('**/requirements_nuitka.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-pip-

      - name: Install dependencies and configure pywin32
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_nuitka.txt
          python (Get-Command pywin32_postinstall.py).Source -install
        shell: pwsh

      # 核心步骤 1: 使用纯 ASCII 文件名进行 Nuitka 编译
      - name: Build application with Nuitka
        run: |
          python -m nuitka --standalone --windows-disable-console `
            --output-dir="${{ matrix.output-dir-name }}" `
            --windows-icon-from-ico="icon.ico" `
            --include-data-file="icon.ico=icon.ico" `
            --enable-plugin=tk-inter `
            --product-name="创翔多功能定时播音旗舰版" `
            # --- 核心修正：移除了 --output-filename 参数，让 Nuitka 生成默认的 boyin.exe ---
            boyin.py
        shell: pwsh

      # 核心步骤 2: 将生成的文件重命名为中文名称
      - name: Rename executable
        run: |
          Rename-Item -Path "${{ matrix.output-dir-name }}/boyin.exe" -NewName "创翔多功能定时播音旗舰版.exe"
        shell: pwsh

      # 上传打包好的整个文件夹
      - name: Upload artifact (${{ matrix.artifact-name }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.output-dir-name }}/
